name: aso_design
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex>=0.1
  - _openmp_mutex>=5.1
  - archspec>=0.2.5
  - argcomplete>=3.6.0
  - argh>=0.31.3
  - attrs>=25.3.0
  - bcbio-gff>=0.7.1
  - beautifulsoup4>=4.13.3
  - biopython>=1.85
  - blas
  - blas-devel
  - boltons>=24.0.0
  - bottleneck>=1.4.2
  - brotli-python>=1.1.0
  - bx-python>=0.13.0
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - colorama
  - conda
  - conda-build
  - conda-index
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - cpp-expected
  - distro
  - exceptiongroup
  - filelock
  - fmt
  - frozendict
  - fuzzysearch
  - gffutils
  - gsl=2.5
  - h2
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - iniconfig
  - jinja2
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - keyutils
  - krb5
  - ld_impl_linux-64
  - libarchive
  - libblas
  - libcblas
  - libcurl
  - libedit
  - libev
  - libffi
  - libgcc>=12
  - libgcc-ng>=12
  - libgfortran
  - libgfortran5
  - libgomp
  - libhwloc
  - liblapack
  - liblapacke
  - liblief
  - liblzma
  - liblzma-devel
  - libmamba
  - libmambapy
  - libnghttp2
  - libopenblas
  - libsolv
  - libssh2
  - libstdcxx
  - libstdcxx-ng
  - libuuid
  - libxml2
  - libzlib
  - llvmlite
  - lz4-c
  - markupsafe
  - menuinst
  - more-itertools
  - ncurses
  - nlohmann_json
  - nomkl
  - numba
  - numexpr
  - numpy
  - numpy-base
  - openblas
  - openssl
  - packaging
  - pandas
  - patch
  - patchelf
  - pcre2
  - pip
  - pkginfo
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - psutil
  - py-lief
  - pybind11-abi
  - pycosat
  - pycparser
  - pyfaidx
  - pyparsing
  - pysocks
  - pytest
  - python>=3.11
  - python-dateutil
  - python-libarchive-c
  - python-tzdata
  - python_abi
  - pytz
  - pyvcf3
  - pyyaml
  - readline
  - referencing
  - reproc
  - reproc-cpp
  - requests
  - ripgrep
  - rpds-py
  - ruamel.yaml
  - ruamel.yaml.clib
  - setuptools
  - simdjson
  - simplejson
  - six
  - soupsieve
  - spdlog
  - sqlite
  - tbb
  - tk
  - tomli
  - tqdm
  - truststore
  - typing-extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - xz-gpl-tools
  - xz-tools
  - yaml
  - yaml-cpp
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
      - viennarna==2.7.0