name: aso_design
channels:
  - defaults
dependencies:
  - python=3.11
  - gsl=2.5
  - pytest
  - pandas
  - bioconda::viennarna
  - numba
  - gffutils
  - conda-forge::fuzzysearch
  - bioconda::bcbio-gff
  - tqdm
  - conda-build
