name: Conda CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda with mamaba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: 3.11             # Specify your desired Python version
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          auto-update-conda: false
          environment-file: environment.yml # Use an environment file to define your dependencies
          activate-environment: aso_design       # Name of the conda environment defined in environment.yml

      - name: Install package
        run: |
          pip install -e . --no-deps
      - name: Run tests
        run: |
          python -m pytest
